version: '2'

services:

  sentry_main:
    container_name: "sentry_main"
    image: sentry:latest
    volumes:
      - ./var/sentry:/var/lib/sentry/files
      - ./another_entrypoint.sh:/another_entrypoint.sh
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - SENTRY_SECRET_KEY=$secret_key
      - SENTRY_POSTGRES_HOST=sentry_postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry123
      - SENTRY_REDIS_HOST=sentry_redis
    command: run web
    depends_on:
      - sentry_postgres
      - sentry_redis
      - sentry_memcached

  sentry_postgres:
    container_name: "sentry_postgres"
    image: postgres:latest
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=sentry123

  sentry_redis:
    container_name: "sentry_redis"
    image: redis:latest
    volumes:
      - ./var/redis:/data

  sentry_memcached:
    container_name: "sentry_memcached"
    image: memcached:latest

  sentry_cron:
    container_name: "sentry_cron"
    image: sentry:latest
    volumes:
      - ./var/sentry:/var/lib/sentry/files
    environment:
      - SENTRY_SECRET_KEY=$secret_key
      - SENTRY_POSTGRES_HOST=sentry_postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry123
      - SENTRY_REDIS_HOST=sentry_redis
    entrypoint: ["/entrypoint.sh"]
    command: ["run", "cron"]
    depends_on:
      - sentry_postgres
      - sentry_redis
      - sentry_memcached

  sentry_worker:
    container_name: "sentry_worker"
    image: sentry:latest
    volumes:
      - ./var/sentry:/var/lib/sentry/files
    environment:
      - SENTRY_SECRET_KEY=$secret_key
      - SENTRY_POSTGRES_HOST=sentry_postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry123
      - SENTRY_REDIS_HOST=sentry_redis
    entrypoint: ["/entrypoint.sh"]
    command: ["run", "worker"]
    depends_on:
      - sentry_postgres
      - sentry_redis
      - sentry_memcached
