version: '2'

services:

  sentry_main:
    container_name: "sentry_main"
    image: haoliang/sentry:latest
    volumes:
      - ./var/sentry:/var/lib/sentry/files
      - ./another_entrypoint.sh:/another_entrypoint.sh
    expose:
      - "80"
    environment:
      - SENTRY_SECRET_KEY=$secret_key
      - SENTRY_POSTGRES_HOST=sentry_postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=seiue123
      - SENTRY_REDIS_HOST=sentry_redis
      - SENTRY_WEB_PORT=80
      - VIRTUAL_HOST=sentry.chalk.o
      - VIRTUAL_PORT=80
    entrypoint: /another_entrypoint.sh
    user: 0:0
    command: run web
    depends_on:
      - sentry_postgres
      - sentry_redis
      - sentry_memcached
    networks:
      hub:
        aliases:
          - sentry.chalk.o

  sentry_postgres:
    container_name: "sentry_postgres"
    image: postgres:latest
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=seiue123
    networks:
      - hub

  sentry_redis:
    container_name: "sentry_redis"
    image: redis:latest
    volumes:
      - ./var/redis:/data
    networks:
      - hub

  sentry_memcached:
    container_name: "sentry_memcached"
    image: memcached:latest
    networks:
      - hub

  sentry_cron:
    container_name: "sentry_cron"
    image: haoliang/sentry:latest
    volumes:
      - ./var/sentry:/var/lib/sentry/files
    environment:
      - SENTRY_SECRET_KEY=$secret_key
      - SENTRY_POSTGRES_HOST=sentry_postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=seiue123
      - SENTRY_REDIS_HOST=sentry_redis
    command: run cron
    depends_on:
      - sentry_postgres
      - sentry_redis
      - sentry_memcached
    networks:
      - hub

  sentry_worker:
    container_name: "sentry_worker"
    image: haoliang/sentry:latest
    volumes:
      - ./var/sentry:/var/lib/sentry/files
    environment:
      - SENTRY_SECRET_KEY=$secret_key
      - SENTRY_POSTGRES_HOST=sentry_postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=seiue123
      - SENTRY_REDIS_HOST=sentry_redis
    command: run worker
    depends_on:
      - sentry_postgres
      - sentry_redis
      - sentry_memcached
    networks:
      - hub

networks:
    hub:
        external: true
